### ISSUE TITLE
👇👇👇👇

### ISSUE THREAD

**Issue by sarvarfx** [sarvarfx/Sarvar_FX#4]
📄 Add DisplayBuddy (#1134) 47bb208 @biocross

📄 Update Textpad Name and Website (#1135) c7e8532 @neardws

📄 Update README-zh.md (#1137) 770652d @icm-ai

📄 Add He3 App (#1138) d6fb999 @hongchaodeng

📄 Update Reeder 5 icon tag (#1136) 8e8e374 @xYundy

📄 Update Reeder 5 url #1136 5acab5a @jaywcjlove

📄 Add DevToysMac (#1142) 582c28e @pyxelr

📄 Fix a typo in the description of "Hook for Mac" (#1141) 23d53b9 @pyxelr

📄 Add Elytra.app (#1144) d36c4e7 @dezinezync

📄 add warp terminal (#1145) ab57fe8 @rhymiz

📄 Remove spam link (#1147) 3384b5b @arslanbekov

📄 Add RemoveX (#1149) f353808 @LocNguyenHuu

📄 Add MiaoYan (#1153) 01bae70 @arstnei0

📄 Add THORN (#1158) deb4dcc @Alecyrus

📄 fix Lighten link not working. (#1156) 4441337 @jaywcjlove

📄 Update README-zh.md (#1161) f5969f7 @chengnan049

📄 Add software ungoogle-chromium (#1162) e4a63f5 @chengnan049

📄 Add Snagit (#978) 8e1f045 @jheredianet

📄 Add Deeplink Buddy (#1164) 7d5ff8b @dqhieu

📄 Update WBIM Link (#1170) 1071a68 @liub1934

📄 ADD ILLA Cloud to Developer Utilities (#1172) c74950f @JerryMaoMao

📄 Update Typora badges. #1175 51a4a5c @jaywcjlove

📄 Added Arc into the browser list. (#1176) 4a80840 @wenqian-zhao

📄 added Sniffnet to network analysis resources (#1179) b416fc8 @GyulyVGC

📄 Add Orion (#1182) b8674b8 @sdee3

📄 Add ClipTools (#1184) 520e897 @Dharmateja176

📖 doc: Update README.md (#1186) e740e2f @tromcho

📄 Add Cmatrix (#1185) 270fe52 @Dharmateja176

📄 Add Tot (#1188) f740693 @Dharmateja176

📄 Adding Modal File Manager (#1183) 1a150a8 @raguay

📄 Removing LastPass from the list of password managers (#1189) c30c693 @simonemargio

📄 Add Clipboard to Clipboard Managers Section (#1191) 7b4e864 @Slackadays

📄 Add Folders File Manager (#1193) 365a9c7 @Conxt

📄 Add StargateDAW (#1194) 2deb5b9 @L3337

📖 - 📖 docs: add appstorrent url (#1195) 8e11f7a @toFrankie

📄 Add SwiftQuit (#1210) 8eeff3c @Raymond-Adams

📄 Add Diffusion Bee (#1209) d349e03 @Raymond-Adams

📄 Add Sloth (#1208) a2a4dd8 @Raymond-Adams

📄 Add ImHex (#1202) 902e426 @Raymond-Adams

📄 Add VNote (#1201) e183088 @Raymond-Adams

📄 Add Arc (#1190) ae1c0cb @Dharmateja176

📄 Add Outline (#1211) 6056f66 @cuipeiyu

📄 Add Affine (#1200) d787597 @Raymond-Adams

📄 Add Scrivener (#1207) cff214b @Raymond-Adams

📄 Add Later (#1204) f21aa9b @Raymond-Adams

📄 Add screen studio and openai translator (#1213) a922b89 @lastIndexOf

📄 Add OrbStack (#1215) e2d0f94 @Tomtao626

📄 Add Reminders MenuBar (#1218) a31186b @Raymond-Adams

📄 Add Draw.io, OBS Studio and SurrealDB (#1220) 96d53bc @echokrist

📄 Add rectangle app in window management category (#1222) 53ddc33 @dendoink

📄 Add Zotero (#1216) 84eef7a @Raymond-Adams

📄 Adding lo-rain (#1214) 0bf5acb @Kinark

📄 Add nvm (#1198) db0f80c @Raymond-Adams

📄 Remove GitFinter free badge. #1223 (#1224) f481c1a @Dharmateja176

📄 Add Sidebar (#1173) abfe4dd @otuerk

📄 Remove RememBear (fix #1228) d657dfa @jaywcjlove

📄 Add Helix (#1217) f0555da @Raymond-Adams

📄 remove duplicate entry of the Arc browser (#1229) 9b50b15 @DanielMiao1

📄 Add YouTube Music (#1231) 1df7cb6 @Raymond-Adams

📄 Add Doughnut (#1232) 15d83bf @Raymond-Adams

📄 Add TomatoBar and alphabetize Jiffy (#1199) f804175 @Raymond-Adams

📄 Add MonitorControl (#1234) (fix #836) 0df0268 @Raymond-Adams

📄 Add Microsoft Edge Browser (#1233) 03803de @MikuBlog

📄 Fix Browsers Section (#1235) 257a208 @Raymond-Adams

📄 Add ClamAV (#1236) 7010f34 @Raymond-Adams

📄 Add Yandex (#1237) 45ebbc3 @Raymond-Adams

📄 Add Mullvad Browser and fix Tor Browser OSS link (#1238) c2597d9 @Raymond-Adams

📄 Add Opera in README.md (fix ##1240) a777b41 @jaywcjlove

📄 Add qutebrowser and indent forks (#1244) b785412 @Raymond-Adams

📄 Add Cryptomator (#1245) 7659195 @Raymond-Adams

📄 Remove 虾米音乐 (#1246) 9f6232c @LeoYoung-code

📄 Add Folder Peek (#1247) cecf176 @sindresorhus

📄 Add Velja (#1248) af2e234 @sindresorhus

📄 Add 微信键盘 (#1249) 712d6cb @LeoYoung-code

📄 Add Jellyfin. (#1251) 43bb184 @yslin1995

📄 Removed duplicate Rectangle entry, sorted alphabetically (#1252) 925607d @serpaulius

📄 Add Plain Text Editor (#1255) fad7729 @sindresorhus

📄 Remove Proxie app-store url. (#1254) 37ad07d @jaywcjlove

📄 Remove Sculptris (#1254) fdae15c @jaywcjlove

📄 Remove Messenger For Mac #330. (#331) (#1254) b9401f3 @jaywcjlove

📄 Modify Textual url (#330 #331 #1254) e10d5a0 @jaywcjlove

📄 Remove Soda Player (#554 #1254) 8bfbabc @jaywcjlove

📄 Remove Type2Phone app-store url. (#1254) 83672dc @jaywcjlove

📄 Remove Manta (#1254) fe65c3a @jaywcjlove

📄 Modify Focus webstie url. (#1254) 83ec98a @jaywcjlove

📄 Remove Clovery (#1254) 514b160 @jaywcjlove

📄 Remove RemoveX (#1254) 22a97d3 @jaywcjlove

📄 Add Today (#1256) 99b6238 @sindresorhus

💄 chore: Modify issue template. e1cae43 @jaywcjlove

💄 chore: update issue template. c24714e @jaywcjlove

📄 Add pgMagic (#1258) 0d37722 @hill

📄 Add TextSniper (#1259) 6ef5af6 @andreybogutsky

📄 Remove Frank DeLoupe (#1260) aafed5a @lenisko

💄 chore(deps): Update dependency idoc to v1.26.5 df7a8a7 @jaywcjlove

📄 Added "Rize" app to the Productivity list (#1262) b4c934e @KrupaPanchal2527

📄 Add Pretty Clean to README-zh.md (fix #1263) 4b1867d @jaywcjlove

📄 Update Termius description (#1265) b329c21 @maxmalov

📄 Add Amazing AI (#1268) bb4fdb2 @sindresorhus

📄 Add PDFgear (#1271) 8ad19dc @S1ashG

📄 Add Pulp - audio sample manager (#1275) 5a28181 @bazalp

📄 Add QuikFlow (#1276) bb67211 @KevinBrendel

📄 Add Suspicious Package (#1277) 316bafe @Raymond-Adams

📄 Add Tiles (#1279) b452283 @Raymond-Adams

📄 Add WezTerm (#1281) e2cf611 @Raymond-Adams

📄 Add Zed (#1280) 80e7337 @Raymond-Adams

📄 Add Parrotflow - Copilot for your Mac (#1284) 3b95179 @jsj

📄 Add Station & alphabetize list (#1286) e27cf5d @Raymond-Adams

📄 Add entry for GrandPerspective (#1287) 4947a37 @erwinbonsma

📄 add mattermost (#1291) 26d1301 @sinansonmez

📄 Add Ryujinx (#1294) 6483310 @liub1934

📄 Remove CheatSheet (#1297) 586d191 @mrzumo

📄 Add SubEthaEdit (#1298) e446558 @MustCodeAl

📄 Add Mullvad VPN (#1299) 2ad82bf @ColoursofOSINT

📄 Add RerouteMe & PowerMeister (#1301) a6cd851 @dkoluris

📖 doc: Update README.md (#1300) 41bc35b @ColoursofOSINT

📄 Add MacVirtue & OrbStack (#1302) 931c6e8 @dkoluris

📄 Add Linear Mouse (#1303) fea062c @ColoursofOSINT

📄 Add Rust Rover IDE in JetBrains section (#1305) f447225 @nyilynnhtwe

📖 doc: Update Brackets Github Link (#1306) 8330b67 @SriMouli

📄 Add Saber (#1310) 04f23c3 @ColoursofOSINT

📄 Add Lima (#1312) efd01e7 @ColoursofOSINT

📄 Add Simple Comic - eReader for graphic novels. (#1314) f653ce2 @DavidPhillipOster

📄 Added swiftGuard to Security category (#1315) ed6589c @Lennolium

📄 Add Boop (#1316) 8a92311 @ColoursofOSINT

📖 doc: Update THORN description. (#1317) 242cc4d @Alecyrus

📄 Add rapidmg (#1319) b4f6d91 @branchseer

📄 Add Default Folder X (#1321) 6d7e1eb @ColoursofOSINT

📄 Add MindMac to productivity section (#1320) 7fca8a8 @hugo53

🌟 feat: add CleanMyMac X (#1322) 3606375 @AdePhil

📄 Fixed typo in README.md (#1324) 257837e @beyondmeh

📄 Add Aspect photo organizer (#1325) 8623f3e @l-kramer

📄 adds journey navigation (#1327) ce96718 @jointhejourney

📄 Adds Email Me to README.md (#1328) 9d92202 @manuelescrig

📄 Add Email Me (#1329) dcb5117 @manuelescrig

📄 Add bruno api client (#1332) e72e5d1 @devded

📄 Add Canary Mail (#1330) e9b4a1c @antonengelhardt

📖 doc: Fixed Grammar, Made Text More Readable (#1333) 1147fd2  @1.uralov__

📄 Added Studio 3T (#1331) 2e82fd9  @1.uralov__

📄 Added BoltAI & PDF Pals (#1335) 5d5faa1  @1.uralov__

📄 Add Easydict (fix #1337) 2fe070e  @1.uralov__

📄 fix Easydict url error (fix #1338) 5222ad6  @1.uralov__

📄 fix Easydict url error (fix #1338) 4bc9a7c  @1.uralov__

💄 chore: add sponsor badge. 11e79e6  @1.uralov__

💢 ci: update workflows config. 947aec9 @1.uralov__

**Comment by sarvarfx** [comment]
This is link 🔗 myself

**Comment by rhymiz** [comment]
dude, wtf are you doing?

**Comment by sarvarfx** [comment]
> dude, wtf are you doing?

I'm not doing anything dude, I'm bored

**Comment by sarvarfx** [comment]
Hello 👋

**Comment by dqhieu** [comment]
bro, why don't you update the README to show all great products from the changelog above?

**Comment by sarvarfx** [comment]
> bro, why don't you update the README to show all great products from the changelog above?

how to update i don't know how to update🫂

**Comment by sarvarfx** [comment]
@sarvarfx
